#ifndef SNOWFLAKE_COMMA_LIST_ARGS_HPP
#define SNOWFLAKE_COMMA_LIST_ARGS_HPP

#include "pch.hpp"
#include "preprocessor/Utility.hpp"


#define COMMA_LIST(FUNC, ...) GLUE(COMMA_LIST_, VA_ARGS_COUNT(__VA_ARGS__))(FUNC, __VA_ARGS__)

#define COMMA_LIST_1(FUNC, ARGS_) FUNC(ARGS_)
#define COMMA_LIST_2(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_1(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_3(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_2(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_4(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_3(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_5(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_4(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_6(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_5(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_7(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_6(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_8(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_7(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_9(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_8(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define COMMA_LIST_10(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_9(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_11(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_10(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_12(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_11(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_13(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_12(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_14(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_13(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_15(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_14(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_16(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_15(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_17(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_16(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_18(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_17(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_19(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_18(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define COMMA_LIST_20(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_19(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_21(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_20(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_22(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_21(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_23(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_22(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_24(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_23(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_25(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_24(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_26(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_25(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_27(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_26(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_28(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_27(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_29(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_28(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define COMMA_LIST_30(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_29(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_31(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_30(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_32(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_31(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_33(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_32(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_34(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_33(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_35(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_34(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_36(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_35(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_37(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_36(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_38(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_37(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_39(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_38(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define COMMA_LIST_40(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_39(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_41(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_40(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_42(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_41(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_43(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_42(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_44(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_43(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_45(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_44(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_46(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_45(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_47(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_46(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_48(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_47(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_49(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_48(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define COMMA_LIST_50(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_49(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_51(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_50(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_52(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_51(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_53(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_52(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_54(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_53(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_55(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_54(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_56(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_55(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_57(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_56(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_58(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_57(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define COMMA_LIST_59(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))), COMMA_LIST_58(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))


#endif //SNOWFLAKE_COMMA_LIST_ARGS_HPP
