#ifndef SNOWFLAKE_FOR_EACH_ARG_HPP
#define SNOWFLAKE_FOR_EACH_ARG_HPP

/**
* @file ForEachArg.hpp
* @brief A compile time preprocessor for each macro.
*
* HOW TO USE:
*   Use the FOR_EACH_ARG(FUNC, ...) macro. The first parameter is the function/macro that will
*   be called for each variadic argument. Do NOT use the macros with numbers. The macro supports
*   up to 60 variadic arguments.
*
* LINKS & SOURCES:
*   - https://stackoverflow.com/questions/44479282/preprocessor-concatenate-string-to-each-argument-in-va-args
*/

#include "pch.hpp"
#include "preprocessor/Utility.hpp"

#define FOR_EACH_ARG(FUNC, ...) GLUE(FOR_EACH_ARG_, VA_ARGS_COUNT(__VA_ARGS__))(FUNC, __VA_ARGS__)

#define FOR_EACH_ARG_1(FUNC, ARGS_) FUNC(ARGS_)
#define FOR_EACH_ARG_2(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_1(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_3(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_2(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_4(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_3(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_5(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_4(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_6(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_5(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_7(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_6(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_8(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_7(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_9(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_8(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define FOR_EACH_ARG_10(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_9(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_11(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_10(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_12(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_11(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_13(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_12(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_14(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_13(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_15(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_14(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_16(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_15(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_17(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_16(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_18(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_17(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_19(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_18(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define FOR_EACH_ARG_20(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_19(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_21(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_20(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_22(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_21(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_23(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_22(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_24(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_23(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_25(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_24(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_26(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_25(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_27(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_26(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_28(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_27(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_29(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_28(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define FOR_EACH_ARG_30(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_29(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_31(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_30(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_32(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_31(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_33(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_32(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_34(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_33(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_35(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_34(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_36(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_35(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_37(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_36(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_38(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_37(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_39(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_38(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define FOR_EACH_ARG_40(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_39(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_41(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_40(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_42(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_41(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_43(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_42(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_44(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_43(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_45(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_44(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_46(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_45(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_47(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_46(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_48(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_47(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_49(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_48(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#define FOR_EACH_ARG_50(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_49(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_51(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_50(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_52(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_51(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_53(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_52(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_54(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_53(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_55(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_54(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_56(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_55(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_57(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_56(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_58(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_57(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))
#define FOR_EACH_ARG_59(FUNC, ...) FUNC(FIRST_ARG (VA_ARGS_EXPAND(__VA_ARGS__))) FOR_EACH_ARG_58(FUNC,TUPLE_TAIL_ARGS( VA_ARGS_EXPAND(__VA_ARGS__)))

#endif //SNOWFLAKE_FOR_EACH_ARG_HPP
